using System.Globalization;
using System.Text;
using System.Text.Json;

namespace SshDockerBackup.Core.Backup;

/// <summary>Compose's view of a container, taken from the labels it stamps on what it creates.</summary>
public sealed record ComposeMetadata(string? Project, string? Service, string? WorkingDir, string? ConfigFile)
{
    /// <summary>True when this container was created by compose rather than by hand.</summary>
    public bool IsComposeManaged => !string.IsNullOrWhiteSpace(Project);
}

/// <summary>
/// Turns a container's `docker inspect` output into a docker-compose service definition, so a
/// restore is "compose up" rather than rebuilding the container by hand in the DSM UI.
///
/// This is deliberately best-effort. Compose cannot express everything inspect reports, so the raw
/// inspect JSON is archived alongside it and stays the authoritative record.
/// </summary>
public static class ComposeGenerator
{
    public static string Generate(string inspectJson, string containerName)
    {
        using var doc = JsonDocument.Parse(inspectJson);

        var container = doc.RootElement.ValueKind == JsonValueKind.Array
            ? doc.RootElement.EnumerateArray().FirstOrDefault()
            : doc.RootElement;

        if (container.ValueKind != JsonValueKind.Object)
            throw new InvalidOperationException("Unexpected inspect payload.");

        var service = SanitiseServiceName(containerName);
        var config = Child(container, "Config");
        var hostConfig = Child(container, "HostConfig");

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by SshDockerBackup from `docker inspect`.");
        sb.AppendLine("# Review before use: secrets from the container environment are reproduced verbatim,");
        sb.AppendLine("# and options compose cannot express are omitted. See the archived .inspect.json");
        sb.AppendLine("# for the complete original definition.");
        sb.AppendLine();
        sb.AppendLine("services:");
        sb.Append("  ").Append(service).AppendLine(":");

        var image = Str(config, "Image");
        if (!string.IsNullOrWhiteSpace(image))
            sb.Append("    image: ").AppendLine(Scalar(image));

        sb.Append("    container_name: ").AppendLine(Scalar(containerName));

        var restart = RestartPolicy(hostConfig);
        if (restart is not null)
            sb.Append("    restart: ").AppendLine(restart);

        // Omitting these silently changes how the process starts: a relative command or a config
        // file looked up next to the working directory stops resolving, and the container exits
        // moments after compose reports it started.
        var workingDir = Str(config, "WorkingDir");
        if (!string.IsNullOrWhiteSpace(workingDir))
            sb.Append("    working_dir: ").AppendLine(Scalar(workingDir));

        var user = Str(config, "User");
        if (!string.IsNullOrWhiteSpace(user))
            sb.Append("    user: ").AppendLine(Scalar(user));

        if (Bool(hostConfig, "Privileged"))
            sb.AppendLine("    privileged: true");

        // Networking has to be reproduced exactly or containers come back isolated from their
        // peers: a web app on a fresh compose-default network cannot be reached by the tunnel
        // container that fronts it, even though both start cleanly.
        var networkMode = Str(hostConfig, "NetworkMode");
        var attachedNetworks = AttachedNetworks(container);

        if (networkMode is "host" or "none")
        {
            sb.Append("    network_mode: ").AppendLine(Scalar(networkMode));
            attachedNetworks.Clear();
        }
        else if (attachedNetworks is ["bridge"])
        {
            // Docker's own default bridge, which is not the same thing as compose's
            // <project>_default network.
            sb.AppendLine("    network_mode: bridge");
            attachedNetworks.Clear();
        }
        else
        {
            AppendStringList(sb, "networks", attachedNetworks);
        }

        AppendStringList(sb, "environment", Array(config, "Env"));
        AppendPorts(sb, hostConfig);
        AppendVolumes(sb, container);
        AppendStringList(sb, "cap_add", Array(hostConfig, "CapAdd"));
        AppendStringList(sb, "dns", Array(hostConfig, "Dns"));
        AppendStringList(sb, "extra_hosts", Array(hostConfig, "ExtraHosts"));
        AppendHealthcheck(sb, config);
        AppendDevices(sb, hostConfig);
        AppendLabels(sb, config);
        AppendCommand(sb, config);

        AppendTopLevelVolumes(sb, container);
        AppendTopLevelNetworks(sb, attachedNetworks);
        return sb.ToString();
    }

    /// <summary>Every network the container is actually attached to, in declaration order.</summary>
    public static List<string> AttachedNetworks(JsonElement container)
    {
        if (container.ValueKind != JsonValueKind.Object) return [];
        if (!container.TryGetProperty("NetworkSettings", out var settings)) return [];
        if (!settings.TryGetProperty("Networks", out var networks) ||
            networks.ValueKind != JsonValueKind.Object)
            return [];

        return [.. networks.EnumerateObject().Select(p => p.Name).Where(n => n.Length > 0)];
    }

    /// <summary>
    /// Compose's own labels, which say which project and service a container belonged to and where
    /// the project was defined. Null throughout for a container that compose did not create.
    /// </summary>
    public static ComposeMetadata ReadComposeMetadata(string inspectJson)
    {
        try
        {
            using var doc = JsonDocument.Parse(inspectJson);
            var container = doc.RootElement.ValueKind == JsonValueKind.Array
                ? doc.RootElement.EnumerateArray().FirstOrDefault()
                : doc.RootElement;

            if (container.ValueKind != JsonValueKind.Object) return new ComposeMetadata(null, null, null, null);
            if (!container.TryGetProperty("Config", out var config)) return new ComposeMetadata(null, null, null, null);
            if (!config.TryGetProperty("Labels", out var labels) || labels.ValueKind != JsonValueKind.Object)
                return new ComposeMetadata(null, null, null, null);

            string? Label(string name) =>
                labels.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.String
                    ? value.GetString()
                    : null;

            // config_files can list several files; the first is the project's primary one.
            var configFiles = Label("com.docker.compose.project.config_files");
            var primary = configFiles?.Split(',').Select(f => f.Trim()).FirstOrDefault(f => f.Length > 0);

            return new ComposeMetadata(
                Label("com.docker.compose.project"),
                Label("com.docker.compose.service"),
                Label("com.docker.compose.project.working_dir"),
                primary);
        }
        catch (JsonException)
        {
            return new ComposeMetadata(null, null, null, null);
        }
    }

    /// <summary>Reads the attached networks straight from a raw inspect payload.</summary>
    public static IReadOnlyList<string> ReadNetworks(string inspectJson)
    {
        try
        {
            using var doc = JsonDocument.Parse(inspectJson);
            var container = doc.RootElement.ValueKind == JsonValueKind.Array
                ? doc.RootElement.EnumerateArray().FirstOrDefault()
                : doc.RootElement;

            var mode = container.TryGetProperty("HostConfig", out var hostConfig)
                ? Str(hostConfig, "NetworkMode")
                : "";

            if (mode is "host" or "none") return [];

            var attached = AttachedNetworks(container);
            return attached is ["bridge"] ? [] : attached;
        }
        catch (JsonException)
        {
            return [];
        }
    }

    /// <summary>
    /// Declared external so compose joins the existing network rather than inventing a new one.
    /// Restore creates any that are missing beforehand, which covers a fresh host too.
    /// </summary>
    private static void AppendTopLevelNetworks(StringBuilder sb, List<string> networks)
    {
        if (networks.Count == 0) return;

        sb.AppendLine();
        sb.AppendLine("networks:");
        foreach (var name in networks.Distinct(StringComparer.Ordinal))
        {
            sb.Append("  ").Append(Scalar(name)).AppendLine(":");
            sb.AppendLine("    external: true");
        }
    }

    private static void AppendCommand(StringBuilder sb, JsonElement config)
    {
        var entrypoint = Array(config, "Entrypoint");
        if (entrypoint.Count > 0)
            AppendStringList(sb, "entrypoint", entrypoint);

        var cmd = Array(config, "Cmd");
        if (cmd.Count > 0)
            AppendStringList(sb, "command", cmd);
    }

    private static void AppendPorts(StringBuilder sb, JsonElement hostConfig)
    {
        if (!hostConfig.TryGetProperty("PortBindings", out var bindings) ||
            bindings.ValueKind != JsonValueKind.Object)
            return;

        var entries = new List<string>();
        foreach (var binding in bindings.EnumerateObject())
        {
            // Key looks like "80/tcp"; value is a list of {HostIp, HostPort}.
            var parts = binding.Name.Split('/');
            var containerPort = parts[0];
            var protocol = parts.Length > 1 ? parts[1] : "tcp";

            if (binding.Value.ValueKind != JsonValueKind.Array) continue;

            foreach (var host in binding.Value.EnumerateArray())
            {
                var hostPort = Str(host, "HostPort");
                var hostIp = Str(host, "HostIp");
                if (string.IsNullOrWhiteSpace(hostPort)) continue;

                var mapping = string.IsNullOrWhiteSpace(hostIp) || hostIp is "0.0.0.0"
                    ? $"{hostPort}:{containerPort}"
                    : $"{hostIp}:{hostPort}:{containerPort}";

                if (protocol != "tcp") mapping += "/" + protocol;
                entries.Add(mapping);
            }
        }

        AppendStringList(sb, "ports", entries);
    }

    private static void AppendVolumes(StringBuilder sb, JsonElement container)
    {
        if (!container.TryGetProperty("Mounts", out var mounts) || mounts.ValueKind != JsonValueKind.Array)
            return;

        var entries = new List<string>();
        foreach (var mount in mounts.EnumerateArray())
        {
            var type = Str(mount, "Type");
            var destination = Str(mount, "Destination");
            if (string.IsNullOrWhiteSpace(destination)) continue;

            var readWrite = mount.TryGetProperty("RW", out var rw) && rw.ValueKind == JsonValueKind.True;
            var suffix = readWrite ? "" : ":ro";

            var source = type switch
            {
                "volume" => Str(mount, "Name"),
                "bind" => Str(mount, "Source"),
                _ => "",
            };

            if (string.IsNullOrWhiteSpace(source)) continue;
            entries.Add($"{source}:{destination}{suffix}");
        }

        AppendStringList(sb, "volumes", entries);
    }

    /// <summary>Named volumes must also be declared at the top level or compose will not create them.</summary>
    private static void AppendTopLevelVolumes(StringBuilder sb, JsonElement container)
    {
        if (!container.TryGetProperty("Mounts", out var mounts) || mounts.ValueKind != JsonValueKind.Array)
            return;

        var named = mounts.EnumerateArray()
            .Where(m => Str(m, "Type") == "volume")
            .Select(m => Str(m, "Name"))
            .Where(n => !string.IsNullOrWhiteSpace(n))
            .Distinct(StringComparer.Ordinal)
            .ToList();

        if (named.Count == 0) return;

        sb.AppendLine();
        sb.AppendLine("volumes:");
        foreach (var name in named)
        {
            sb.Append("  ").Append(Scalar(name)).AppendLine(":");
            sb.AppendLine("    external: true");
        }
    }

    private static void AppendLabels(StringBuilder sb, JsonElement config)
    {
        if (!config.TryGetProperty("Labels", out var labels) || labels.ValueKind != JsonValueKind.Object)
            return;

        // Compose stamps its own labels on managed containers; copying them back confuses it.
        var entries = labels.EnumerateObject()
            .Where(p => !p.Name.StartsWith("com.docker.compose.", StringComparison.Ordinal))
            .Select(p => $"{p.Name}={p.Value.GetString() ?? ""}")
            .ToList();

        AppendStringList(sb, "labels", entries);
    }

    /// <summary>
    /// Without this the container still runs, but reports no health at all: Container Manager shows
    /// it merely as up, and anything waiting on service_healthy never gets its signal.
    /// </summary>
    private static void AppendHealthcheck(StringBuilder sb, JsonElement config)
    {
        if (config.ValueKind != JsonValueKind.Object) return;
        if (!config.TryGetProperty("Healthcheck", out var health) || health.ValueKind != JsonValueKind.Object) return;

        var test = Array(health, "Test");
        if (test.Count == 0) return;

        // Docker records an explicitly disabled check as ["NONE"].
        if (test is ["NONE"])
        {
            sb.AppendLine("    healthcheck:");
            sb.AppendLine("      disable: true");
            return;
        }

        sb.AppendLine("    healthcheck:");
        sb.AppendLine("      test:");
        foreach (var part in test)
            sb.Append("        - ").AppendLine(Scalar(part));

        AppendDuration(sb, health, "Interval", "interval");
        AppendDuration(sb, health, "Timeout", "timeout");
        AppendDuration(sb, health, "StartPeriod", "start_period");

        if (health.TryGetProperty("Retries", out var retries) &&
            retries.ValueKind == JsonValueKind.Number && retries.GetInt32() > 0)
        {
            sb.Append("      retries: ").AppendLine(retries.GetInt32().ToString(CultureInfo.InvariantCulture));
        }
    }

    /// <summary>Docker stores these as nanoseconds; compose wants a duration such as "30s".</summary>
    private static void AppendDuration(StringBuilder sb, JsonElement parent, string dockerName, string composeName)
    {
        if (!parent.TryGetProperty(dockerName, out var value) || value.ValueKind != JsonValueKind.Number) return;

        var nanoseconds = value.GetInt64();
        if (nanoseconds <= 0) return;

        var seconds = nanoseconds / 1_000_000_000d;
        sb.Append("      ").Append(composeName).Append(": ")
          .AppendLine(seconds.ToString("0.##", CultureInfo.InvariantCulture) + "s");
    }

    private static void AppendDevices(StringBuilder sb, JsonElement hostConfig)
    {
        if (!hostConfig.TryGetProperty("Devices", out var devices) || devices.ValueKind != JsonValueKind.Array)
            return;

        var entries = new List<string>();
        foreach (var device in devices.EnumerateArray())
        {
            var onHost = Str(device, "PathOnHost");
            var inContainer = Str(device, "PathInContainer");
            if (string.IsNullOrWhiteSpace(onHost)) continue;
            entries.Add(string.IsNullOrWhiteSpace(inContainer) ? onHost : $"{onHost}:{inContainer}");
        }

        AppendStringList(sb, "devices", entries);
    }

    private static void AppendStringList(StringBuilder sb, string key, IReadOnlyCollection<string> values)
    {
        if (values.Count == 0) return;

        sb.Append("    ").Append(key).AppendLine(":");
        foreach (var value in values)
            sb.Append("      - ").AppendLine(Scalar(value));
    }

    private static string? RestartPolicy(JsonElement hostConfig)
    {
        if (!hostConfig.TryGetProperty("RestartPolicy", out var policy)) return null;

        var name = Str(policy, "Name");
        if (string.IsNullOrWhiteSpace(name) || name == "no") return null;

        if (name != "on-failure") return name;

        var retries = policy.TryGetProperty("MaximumRetryCount", out var max) &&
                      max.ValueKind == JsonValueKind.Number
            ? max.GetInt32()
            : 0;

        return retries > 0
            ? "on-failure:" + retries.ToString(CultureInfo.InvariantCulture)
            : "on-failure";
    }

    /// <summary>Always double-quote. It is verbose but immune to YAML's many implicit-type traps.</summary>
    private static string Scalar(string value)
    {
        var escaped = value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "", StringComparison.Ordinal);
        return "\"" + escaped + "\"";
    }

    private static string SanitiseServiceName(string name)
    {
        var cleaned = new string(name.Select(c => char.IsLetterOrDigit(c) || c is '-' or '_' ? c : '-').ToArray())
            .Trim('-');
        return cleaned.Length == 0 ? "service" : cleaned.ToLowerInvariant();
    }

    private static JsonElement Child(JsonElement parent, string name) =>
        parent.TryGetProperty(name, out var value) ? value : default;

    private static string Str(JsonElement element, string name) =>
        element.ValueKind == JsonValueKind.Object &&
        element.TryGetProperty(name, out var value) &&
        value.ValueKind == JsonValueKind.String
            ? value.GetString() ?? ""
            : "";

    private static bool Bool(JsonElement element, string name) =>
        element.ValueKind == JsonValueKind.Object &&
        element.TryGetProperty(name, out var value) &&
        value.ValueKind == JsonValueKind.True;

    private static List<string> Array(JsonElement element, string name)
    {
        if (element.ValueKind != JsonValueKind.Object ||
            !element.TryGetProperty(name, out var value) ||
            value.ValueKind != JsonValueKind.Array)
            return [];

        return [.. value.EnumerateArray()
            .Where(v => v.ValueKind == JsonValueKind.String)
            .Select(v => v.GetString() ?? "")];
    }
}
